services:
  db:
    image: postgres:latest
    restart: always
    ports:
    - "5434:5432"
    environment:
      - POSTGRES_USER=mms
      - POSTGRES_PASSWORD=mms
      - POSTGRES_DB=mms
      - PGUSER=mms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 1s
          timeout: 5s
          retries: 10
  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    environment:
      - PORT=8000
      - jwtSecret=ebube2003 
    ports:
      - "8122:8000"
    depends_on:
      - db
    # volumes:
    #   - ./:./

volumes:
  postgres_data: