services:
  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 1s
          timeout: 5s
          retries: 10
  app:
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: mms
      DB_NAME: mms
      DB_PORT: 5432
    ports:
      - "8000:8080"
    depends_on:
      - db
volumes:
  pgdata: